---
os: Visual Studio 2015

version: 2018.08.{build}

clone_depth: 5

environment:
  CTEST_OUTPUT_ON_FAILURE: 1
  matrix:
    - COMPILER: msys2
      PLATFORM: x64
      MSYS2_ARCH: i686
      MSYS2_DIR: msys64
      MSYSTEM: MINGW32
      BIT: 32
      BUILDTOOL: cmake

before_build:
  - git submodule init
  - git submodule update

build_script:
  - set VERBOSE=1
  - '%APPVEYOR_BUILD_FOLDER%\ceammc\distrib\appveyor\install.bat'
