os: Visual Studio 2015

version: 2018.08.{build}

#clone_depth: 5

environment:
    CTEST_OUTPUT_ON_FAILURE: 1
    VCVARS: "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\bin\\vcvars32.bat"
    matrix:
    - COMPILER: msys2
        PLATFORM: x64
        MSYS2_ARCH: x86_64
        MSYS2_DIR: msys64
        MSYSTEM: MINGW64
        BIT: 32
        BUILDTOOL: cmake


install:
    - echo "Intall"

before_build:
    - dir
    - git submodule init
    - git submodule update
    - '%APPVEYOR_BUILD_FOLDER%\ceammc\distrib\appveyor\install.bat'


build_script:
    - set VERBOSE=1
