[package]
name = "net_rust"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
bytes = "1.5.0"
rumqttc = { version = "0.22.0"}
tungstenite = "0.21.0"
url = "2.5.0"

[build-dependencies]
cbindgen = "0.22.0"
