[package]
name = "net_rust"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
bytes = "1.5.0"
rumqttc = { version = "0.22.0", features = ["url"] }
tungstenite = "0.21.0"
url = "2.5.0"
tokio = { version = "1.36", features = ["rt", "rt-multi-thread", "signal", "sync", "fs"] }
tokio-util = { version = "0.7.3", features = ["codec"] }
reqwest = { version = "0.11.11", features =["stream", "multipart"] } 
scraper = "0.19.0"
frankenstein = { version = "0.30.5", features = ["async-http-client"] }  
regex = { version = "1.10.4", default-features = false }
lazy_static = { version = "1.4.0", default-features = false }
tokio-tungstenite = { version ="0.21.0", features = ["native-tls"] }
futures-util = "0.3.30"
log = "0.4.21"
env_logger = "0.11.3"
oauth2 = "4.4.2"
anyhow = "1.0.82"
serde_json = "1.0.115"
homedir = "0.2.1"
nom = "7.1.3"
tempfile = "3.10.1"
symphonia = "0.5.4"
derivative = "2.2.0"

[build-dependencies]
cbindgen = "0.22.0"

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "my_benchmark"
harness = false

