[package]
name = "hw_rust"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib", "cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
c_str_macro = "1.0.3"
gilrs = "0.10.5"

[target.'cfg(windows)'.dependencies]
winprint = {version = "0.1.0", default-features = false, features=[]}
printers = {version = "2.0.0", default-features = false, features=[]}

[target.'cfg(macos)'.dependencies]
cups-sys = "0.1.4"

[build-dependencies]
cbindgen = "0.22.0"
