[package]
name = "hw_rust"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib", "cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cups-sys = "0.1.4"
gilrs = "0.10.5"

[build-dependencies]
cbindgen = "0.22.0"
